/**
 * Intro Scene - Story Part 0
 * Prologue establishing Ryan's character and setting
 */

const IntroScene = {
    id: 'intro',
    name: 'Prologue',
    
    background: 'assets/images/scenes/intro.svg',
    
    description: 'A quiet morning in Compascuum, Drenthe. The world is about to change.',
    
    playerStart: { x: 50, y: 85 },
    
    idleThoughts: [],
    
    hotspots: [],
    
    onEnter: function(game) {
        // Show prologue sequence
        setTimeout(() => {
            game.startDialogue([
                { speaker: '', text: '═══════════════════════════════════════════' },
                { speaker: '', text: '📍 COMPASCUUM, DRENTHE, NETHERLANDS' },
                { speaker: '', text: '📅 February 9, 2026' },
                { speaker: '', text: '⏰ 07:45 AM' },
                { speaker: '', text: '═══════════════════════════════════════════' },
                { speaker: '', text: '' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'Dawn breaks over the Dutch countryside.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'The first light touches the heathlands of Drenthe, painting purple heather in shades of gold.' },
                { speaker: 'Narrator', text: 'Mist rises slowly from the canals, tendrils of white drifting across still water.' },
                { speaker: 'Narrator', text: 'The world is silent except for the distant call of a heron, the rustle of reeds in the breeze.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'In the distance, wind turbines turn methodically, their blades cutting through the morning fog.' },
                { speaker: 'Narrator', text: 'Each rotation hypnotic. Endless. A rhythm older than memory, newer than tomorrow.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'This is Drenthe.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'Quiet. Rural. Unassuming.' },
                { speaker: 'Narrator', text: 'A province forgotten by many. Overlooked by most.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'Ancient dolmens rise from the heath - megalithic tombs five thousand years old.' },
                { speaker: 'Narrator', text: 'Villages with narrow streets and red brick churches dot the landscape.' },
                { speaker: 'Narrator', text: 'Farmers tend their fields. Cyclists pedal along winding paths.' },
                { speaker: 'Narrator', text: 'Life moves slowly here. Deliberately. With purpose.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'But beneath this peaceful surface lies something else entirely...' },
                { speaker: '', text: '' },
                { speaker: '', text: '⸻' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'Scattered across these quiet fields are machines listening to the universe.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'The Westerbork Synthesis Radio Telescope - fourteen massive dishes scanning the heavens.' },
                { speaker: 'Narrator', text: 'Operating since 1970, detecting pulsars, mapping distant galaxies, measuring cosmic background radiation.' },
                { speaker: 'Narrator', text: 'A cathedral of science built on moorland and peat.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'LOFAR - the Low-Frequency Array - over 50,000 antennas spread across Europe.' },
                { speaker: 'Narrator', text: 'Its core here in Drenthe, listening to frequencies no other telescope can hear.' },
                { speaker: 'Narrator', text: 'Detecting signals from the dawn of the universe. Thirteen billion years traveling through space.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'These instruments pioneered techniques that changed the world.' },
                { speaker: 'Narrator', text: 'Signal processing algorithms. Beam-forming techniques. Interference mitigation strategies.' },
                { speaker: 'Narrator', text: 'Methods developed to study distant stars now power the smartphones in our pockets.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'Bluetooth technology - protocols refined right here in the Netherlands.' },
                { speaker: 'Narrator', text: 'WiFi mesh networks. 5G beam-forming. Software-defined radio.' },
                { speaker: 'Narrator', text: 'All born from innovations in these quiet northern fields.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'Wireless technology that now connects five billion devices worldwide...' },
                { speaker: 'Narrator', text: 'Its roots buried deep in the heath of Drenthe.' },
                { speaker: '', text: '' },
                { speaker: '', text: '⸻' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'And in a small farmhouse by a canal...' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'This is Ryan Weylant.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: '55 years old.' },
                { speaker: 'Narrator', text: 'Software developer by trade. Radio enthusiast by passion. Hacker in the truest sense of the word.' },
                { speaker: 'Narrator', text: 'A MacGyver-style problem solver who never met a signal he couldn\'t decode.' },
                { speaker: 'Narrator', text: 'A puzzle he couldn\'t solve. A system he couldn\'t understand.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'He lives in a white farmhouse with a distinctive red roof.' },
                { speaker: 'Narrator', text: 'Right next to the canal, where water reflects clouds and sky.' },
                { speaker: 'Narrator', text: 'Where ducks paddle in summer and ice forms geometric patterns in winter.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'His partner Ies still sleeps upstairs, wrapped in quilts and dreams.' },
                { speaker: 'Narrator', text: 'Their three dogs are curled in their favorite spots throughout the house.' },
                { speaker: 'Narrator', text: 'Tino and Kessy - white fluffy companions - on the couch.' },
                { speaker: 'Narrator', text: 'ET - their energetic pug - sprawled on the rug, snoring softly.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'This is Ryan\'s sanctuary. His fortress of solitude. His home.' },
                { speaker: '', text: '' },
                { speaker: '', text: '⸻' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'But it\'s Ryan\'s garage - his "mancave" - where the real magic happens.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'A treasure trove of technology accumulated over decades.' },
                { speaker: 'Narrator', text: 'Every tool carefully chosen. Every device serving a purpose.' },
                { speaker: 'Narrator', text: 'This is where Ryan thinks. Where he builds. Where he solves the impossible.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: '3D printers wait patiently in the corner, ready to manifest ideas into reality.' },
                { speaker: 'Narrator', text: 'Oscilloscopes line the workbench - Rigol, Tektronix - their screens dark but ready.' },
                { speaker: 'Narrator', text: 'Component drawers organize decades of projects: resistors, capacitors, microcontrollers, sensors.' },
                { speaker: 'Narrator', text: 'Each labeled. Each sorted. A library of possibility.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'On his main workbench sits his arsenal of wireless hacking tools:' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'A HackRF One software-defined radio - capable of transmitting and receiving from 1 MHz to 6 GHz.' },
                { speaker: 'Narrator', text: 'Every protocol, every frequency, every signal within reach.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'A Flipper Zero multi-tool - RFID cloning, infrared control, sub-GHz analysis.' },
                { speaker: 'Narrator', text: 'Small enough to fit in a pocket. Powerful enough to unlock secrets.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'A WiFi Pineapple for network analysis and penetration testing.' },
                { speaker: 'Narrator', text: 'Understanding the hidden architecture of wireless networks.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'Meshtastic long-range communicators running on LoRa frequencies.' },
                { speaker: 'Narrator', text: 'Off-grid messaging when traditional networks fail.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'An SSTV satellite terminal for slow-scan television from space.' },
                { speaker: 'Narrator', text: 'Receiving images from the International Space Station. From weather satellites. From amateur radio operators worldwide.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'Each device a window into the invisible world of electromagnetic waves.' },
                { speaker: 'Narrator', text: 'Each a key to understanding the signals that surround us every moment of every day.' },
                { speaker: '', text: '' },
                { speaker: '', text: '⸻' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'Ryan has spent decades in this quiet corner of the Netherlands.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'Building networks when the internet was young.' },
                { speaker: 'Narrator', text: 'Writing code when software was still an art form.' },
                { speaker: 'Narrator', text: 'Solving puzzles that stumped entire teams of engineers.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'His contacts span the entire country - a network built on trust and shared curiosity:' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'Dr. Henk Visser - radio astronomer at ASTRON, expert in signal processing and pulsar detection.' },
                { speaker: 'Narrator', text: 'Marieke - retired LOFAR technician who pioneered beam-forming algorithms now used in 5G.' },
                { speaker: 'Narrator', text: 'Pieter - former Ericsson engineer who spent fifteen years developing Bluetooth protocols.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'These are Ryan\'s people. Fellow travelers in the electromagnetic spectrum.' },
                { speaker: 'Narrator', text: 'When they have impossible problems, they call Ryan.' },
                { speaker: 'Narrator', text: 'When Ryan has questions, they answer.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'It\'s a community built on mutual respect and endless fascination.' },
                { speaker: 'Narrator', text: 'A hidden network of minds that understand the invisible world.' },
                { speaker: '', text: '' },
                { speaker: '', text: '⸻' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'Ryan\'s philosophy is simple:' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'Be curious. Stay methodical. Never give up.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'If there\'s a signal, he can find it.' },
                { speaker: 'Narrator', text: 'If there\'s a code, he can crack it.' },
                { speaker: 'Narrator', text: 'If there\'s a problem, there\'s always a solution.' },
                { speaker: 'Narrator', text: 'You just have to look. You just have to think. You just have to persist.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'Sometimes the answer takes hours. Sometimes days. Sometimes weeks.' },
                { speaker: 'Narrator', text: 'But the answer is always there, waiting to be found.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'That\'s what Ryan believes.' },
                { speaker: 'Narrator', text: 'That\'s what he\'s always believed.' },
                { speaker: '', text: '' },
                { speaker: '', text: '⸻' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'This morning seems like any other.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'The house is quiet. The dogs are peaceful. Ies sleeps soundly.' },
                { speaker: 'Narrator', text: 'In the kitchen, the espresso machine warms up with familiar sounds - clicks, gurgles, hisses.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'The ritual is always the same:' },
                { speaker: 'Narrator', text: 'Wake up. Make espresso. Check the radio frequencies. Start working.' },
                { speaker: 'Narrator', text: 'A routine perfected over decades. Comfortable. Reliable. Safe.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'Outside, the mist continues to rise from the canal.' },
                { speaker: 'Narrator', text: 'The wind turbines turn their eternal rotation.' },
                { speaker: 'Narrator', text: 'The radio telescopes scan frequencies from the edge of the observable universe.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'Everything as it should be.' },
                { speaker: 'Narrator', text: 'Everything normal.' },
                { speaker: 'Narrator', text: 'Everything perfectly, peacefully ordinary.' },
                { speaker: '', text: '' },
                { speaker: '', text: '⸻' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'But Ryan has no idea.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'No idea that today will change everything.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'That in exactly eighteen minutes, a transmission will arrive.' },
                { speaker: 'Narrator', text: 'A signal that should not exist. Cannot exist. Must not exist.' },
                { speaker: 'Narrator', text: 'A message encrypted with algorithms no civilian should possess.' },
                { speaker: 'Narrator', text: 'Coordinates that point to something impossible. Something that will unravel everything.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'A conspiracy reaching the highest levels of government.' },
                { speaker: 'Narrator', text: 'A secret buried so deep that nations have killed to protect it.' },
                { speaker: 'Narrator', text: 'A truth that will shake the foundations of power in the Netherlands.' },
                { speaker: '', text: '' },
                { speaker: '', text: '⸻' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'Forces are already in motion.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'In a bunker beneath The Hague, screens glow with intercepted data.' },
                { speaker: 'Narrator', text: 'Algorithms calculate probabilities. AI systems monitor every frequency, every network, every whisper.' },
                { speaker: 'Narrator', text: 'People in dark suits make decisions that will cost lives.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'They know someone will intercept the transmission.' },
                { speaker: 'Narrator', text: 'They\'ve planned for this. Prepared for this.' },
                { speaker: 'Narrator', text: 'They have protocols. Assets. Methods that leave no trace.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'But they don\'t know about Ryan Weylant.' },
                { speaker: 'Narrator', text: 'They don\'t know about the man in the farmhouse by the canal.' },
                { speaker: 'Narrator', text: 'They don\'t know what he\'s capable of.' },
                { speaker: '', text: '' },
                { speaker: '', text: '⸻' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'And so the gears turn.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'The gears of something vast and terrible.' },
                { speaker: 'Narrator', text: 'Something that has been running for decades.' },
                { speaker: 'Narrator', text: 'Operation Zerfall - The Fall.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'In the quiet of his farmhouse, drinking his morning espresso...' },
                { speaker: 'Narrator', text: 'Ryan Weylant is about to become the most important person in the Netherlands.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'The only person who can stop what\'s coming.' },
                { speaker: 'Narrator', text: 'The only person who can uncover the truth.' },
                { speaker: 'Narrator', text: 'The only person who stands between conspiracy and catastrophe.' },
                { speaker: '', text: '' },
                { speaker: '', text: '⸻' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'This is how it begins.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'With dawn breaking over Drenthe.' },
                { speaker: 'Narrator', text: 'With mist rising from canals.' },
                { speaker: 'Narrator', text: 'With an espresso machine warming up.' },
                { speaker: '', text: '' },
                { speaker: 'Narrator', text: 'With a man who doesn\'t know he\'s about to save his country.' },
                { speaker: '', text: '' },
                { speaker: '', text: '' },
                { speaker: '', text: '═══════════════════════════════════════════' },
                { speaker: '', text: '🎮 CYBERQUEST: OPERATION ZERFALL' },
                { speaker: '', text: '═══════════════════════════════════════════' },
                { speaker: '', text: '' }
            ]);
            
            // After dialogue, transition to home
            setTimeout(() => {
                game.loadScene('home');
            }, 2000);
        }, 500);
    }
};

// Register scene
if (typeof window.game !== 'undefined') {
    window.game.registerScene(IntroScene);
}
